[package]
name = "rust-faas"
version = "0.1.0"
authors = ["slinkydeveloper <francescoguard@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.8"
serde_json = "1.0"
futures = "0.1.29"
function = { path = "../usr" }